info:
  app:
    name: AronimCloudUserService
    description: Aronim Cloud User Service
    version: 1.0-SNAPSHOT

spring:
  application:
    name: aronim-cloud-user
#  data:
#    mongodb:
#      username: test
#      password: test
server:
  port: 0
